# This default config covers common usages only.
# See /usr/share/doc/machineproxy/examples/machineproxy.example.toml for a full config.

log_level = "warn"
log_file = "" # empty means stderr

[container]

# A list of programs that you want to run locally (or that you cannot install on the remote device)
local_commands = [
    "amp",
    "claude",
    "cline",
    "cn",
    "codex",
    "copilot",
    "gemini",
    "opencode",
    "qpdf",
    "rtk",
    "rg",
]

auto_identity_mounts = true
